<?php
namespace App\Services;
use App\Enums\{BillingType,InvoiceStatus}; use App\Models\{Customer,Delivery,Invoice,LedgerEntry,MealPause,MealSkip}; use Carbon\CarbonInterface; use Illuminate\Support\Facades\DB;
class BillingService {
 public function generate(Customer $customer,CarbonInterface $from,CarbonInterface $to):Invoice{return DB::transaction(function()use($customer,$from,$to){
  $assignment=$customer->plans()->with('mealPlan')->whereDate('starts_on','<=',$to)->where(fn($q)=>$q->whereNull('ends_on')->orWhereDate('ends_on','>=',$from))->latest('starts_on')->firstOrFail();$plan=$assignment->mealPlan;
  $rate=(float)($assignment->rate_override??($plan->billing_type===BillingType::FixedMonthly?$plan->monthly_rate:$plan->daily_rate));$quantity=$plan->billing_type===BillingType::FixedMonthly?1:Delivery::where('customer_id',$customer->id)->whereBetween('delivery_date',[$from,$to])->where('status','delivered')->sum('quantity');$gross=round($quantity*$rate,2);$creditDays=0;$periodDays=max(1,$from->diffInDays($to)+1);
  if($plan->billing_type===BillingType::FixedMonthly&&$plan->credit_pauses){foreach(MealPause::where('customer_id',$customer->id)->whereDate('starts_on','<=',$to)->where(fn($q)=>$q->whereNull('resumes_on')->orWhereDate('resumes_on','>',$from))->get() as $pause){$start=$pause->starts_on->greaterThan($from)?$pause->starts_on:$from;$end=$pause->resumes_on?->copy()->subDay();$end=(!$end||$end->greaterThan($to))?$to:$end;$creditDays+=max(0,$start->diffInDays($end)+1);}}
  if($plan->billing_type===BillingType::FixedMonthly&&$plan->credit_skips)$creditDays+=MealSkip::where('customer_id',$customer->id)->whereBetween('skip_date',[$from,$to])->distinct()->count('skip_date');$creditDays=min($creditDays,$periodDays);$credit=round(($rate/$periodDays)*$creditDays,2);$charges=max(0,round($gross-$credit,2));
  $previous=(float)(LedgerEntry::where('customer_id',$customer->id)->latest('id')->value('running_balance')??$customer->opening_balance);$number='INV-'.$from->format('Ym').'-'.str_pad((string)$customer->id,6,'0',STR_PAD_LEFT);$company=$customer->company;
  $invoice=Invoice::firstOrCreate(['company_id'=>$customer->company_id,'invoice_number'=>$number],['customer_id'=>$customer->id,'period_start'=>$from,'period_end'=>$to,'previous_balance'=>$previous,'current_charges'=>$charges,'total_payable'=>$previous+$charges,'balance'=>$previous+$charges,'status'=>InvoiceStatus::Unpaid,'due_date'=>$to->copy()->addDays($company->invoice_due_days??7),'issued_at'=>now()]);
  if($invoice->wasRecentlyCreated){$invoice->lines()->create(['company_id'=>$customer->company_id,'description'=>$plan->name,'quantity'=>$quantity,'unit_price'=>$rate,'amount'=>$gross,'metadata'=>['billing_type'=>$plan->billing_type->value]]);if($credit>0)$invoice->lines()->create(['company_id'=>$customer->company_id,'description'=>'Pause/skip credit','quantity'=>$creditDays,'unit_price'=>round(-$rate/$periodDays,2),'amount'=>-$credit,'metadata'=>['credit_days'=>$creditDays]]);LedgerEntry::create(['company_id'=>$customer->company_id,'customer_id'=>$customer->id,'type'=>'invoice','debit'=>$charges,'running_balance'=>$previous+$charges,'source_type'=>$invoice->getMorphClass(),'source_id'=>$invoice->id,'description'=>$number]);AuditService::record('invoice.created',$invoice);}return $invoice->load('lines');
 });}
}
