<?php
namespace App\Http\Controllers\Api;
use App\Enums\HandoverStatus; use App\Http\Controllers\Controller; use App\Models\{CashHandover,Customer,Invoice,Payment,Receipt}; use App\Services\AuditService; use Barryvdh\DomPDF\Facade\Pdf; use Illuminate\Http\Request; use Illuminate\Support\Facades\Storage; use Illuminate\Support\Facades\URL;
class FinanceController extends Controller {
 public function customerReceipts(Customer $customer){return response()->json(Receipt::whereHas('payment',fn($q)=>$q->where('customer_id',$customer->id))->with(['payment'=>fn($q)=>$q->select('id','uuid','customer_id','amount','mode','paid_at')])->latest()->paginate(50));}
 public function collections(Request $r){$q=Payment::selectRaw('employee_id, DATE(paid_at) collection_date, mode, COUNT(*) transaction_count, SUM(amount) total')->groupBy('employee_id','collection_date','mode')->orderByDesc('collection_date');return response()->json(['data'=>$q->paginate(50)]);}
 public function handovers(Request $r){return response()->json(CashHandover::with('employee')->latest()->paginate(50));}
 public function storeHandover(Request $r){$d=$r->validate(['uuid'=>'required|uuid','amount_submitted'=>'required|decimal:0,2|gt:0','notes'=>'nullable|string|max:500','idempotency_key'=>'required|string|max:190']);$h=CashHandover::firstOrCreate(['company_id'=>$r->user()->company_id,'idempotency_key'=>$d['idempotency_key']],[...$d,'employee_id'=>$r->user()->id,'status'=>HandoverStatus::Submitted,'submitted_at'=>now()]);AuditService::record('handover.submitted',$h);return response()->json(['data'=>$h],201);}
 public function verify(Request $r,CashHandover $handover){$d=$r->validate(['verified_amount'=>'required|decimal:0,2|min:0','status'=>'required|in:verified,rejected','notes'=>'nullable|string|max:500']);$handover->update([...$d,'variance'=>round((float)$d['verified_amount']-(float)$handover->amount_submitted,2),'verified_by'=>$r->user()->id,'verified_at'=>now()]);AuditService::record('handover.verified',$handover);return response()->json(['data'=>$handover]);}
 public function paymentProof(Request $r,Payment $payment){$r->validate(['proof'=>'required|file|mimes:jpg,jpeg,png,pdf|max:5120']);$payment->update(['proof_path'=>$r->file('proof')->store("private/companies/{$r->user()->company_id}/payment-proofs")]);AuditService::record('payment.proof_uploaded',$payment);return response()->json(['data'=>['uploaded'=>true]]);}
 public function handoverProof(Request $r,CashHandover $handover){$r->validate(['proof'=>'required|file|mimes:jpg,jpeg,png,pdf|max:5120']);$handover->update(['proof_path'=>$r->file('proof')->store("private/companies/{$r->user()->company_id}/handover-proofs")]);AuditService::record('handover.proof_uploaded',$handover);return response()->json(['data'=>['uploaded'=>true]]);}
 public function proof(Request $r,string $type,string $uuid){$model=$type==='payment'?Payment::whereUuid($uuid)->firstOrFail():CashHandover::whereUuid($uuid)->firstOrFail();abort_unless($model->proof_path&&Storage::exists($model->proof_path),404);return Storage::download($model->proof_path);}
 public function receipt(Request $r,Receipt $receipt){$receipt->load('payment.customer.building','payment.customer.room','payment.employee','company');return Pdf::loadView('receipts.payment',['receipt'=>$receipt])->download($receipt->receipt_number.'.pdf');}
 public function share(Request $r,Receipt $receipt){$p=$receipt->payment()->with('customer')->firstOrFail();$company=$receipt->company;$defaultLocale=app()->getLocale();app()->setLocale(in_array($company->locale,['en','ur','ar'])?$company->locale:$defaultLocale);$message=__('messages.payment_received',['receipt'=>$receipt->receipt_number,'currency'=>$company->currency,'amount'=>number_format((float)$p->amount,2)]);app()->setLocale($defaultLocale);$receipt->update(['shared_at'=>now(),'shared_by'=>$r->user()->id]);return response()->json(['data'=>['url'=>'https://wa.me/'.preg_replace('/\D/','',$p->customer->phone ?? '').'?text='.rawurlencode($message),'pdf_url'=>URL::temporarySignedRoute('receipts.shared',now()->addMinutes(30),$receipt)]]);}
 public function invoicePdf(Request $r,Invoice $invoice){$invoice->load(['customer.building','customer.room','lines','company']);return Pdf::loadView('invoices.pdf',['invoice'=>$invoice])->download($invoice->invoice_number.'.pdf');}
 public function shareInvoice(Request $r,Invoice $invoice){$invoice->load('customer');$company=$invoice->company;$defaultLocale=app()->getLocale();app()->setLocale(in_array($company->locale,['en','ur','ar'])?$company->locale:$defaultLocale);$message=__('messages.invoice_ready',['invoice'=>$invoice->invoice_number,'currency'=>$company->currency,'amount'=>number_format((float)$invoice->total_payable,2),'due'=>optional($invoice->due_date)->format('d M Y')??'-']);app()->setLocale($defaultLocale);return response()->json(['data'=>['url'=>'https://wa.me/'.preg_replace('/\D/','',$invoice->customer->phone ?? '').'?text='.rawurlencode($message),'pdf_url'=>URL::temporarySignedRoute('invoices.shared',now()->addMinutes(30),$invoice)]]);}
}
