<?php
namespace App\Http\Controllers\Api;
use App\Enums\{BillingType,DeliveryStatus,PaymentMode}; use App\Http\Controllers\Controller; use App\Models\{Building,Customer,Delivery,Invoice,MealPlan,Payment,Room}; use App\Services\{AuditService,BillingService,PaymentService}; use Illuminate\Http\Request; use Illuminate\Validation\Rule;
class OperationsController extends Controller {
 private function page($q,Request $r){$since=$r->date('updated_since');if($since)$q->where('updated_at','>',$since);return response()->json($q->paginate(min($r->integer('per_page',25),100)));}
 public function buildings(Request $r){return $this->page(Building::query()->withCount('rooms')->orderBy('name'),$r);} public function rooms(Request $r){return $this->page(Room::query()->with('building')->when($r->building_id,fn($q,$id)=>$q->whereHas('building',fn($b)=>$b->where('uuid',$id)))->orderBy('number'),$r);}
 public function customers(Request $r){$q=Customer::with(['building','room'])->when($r->search,fn($q,$s)=>$q->where(fn($x)=>$x->where('name','like',"%$s%")->orWhere('phone','like',"%$s%")->orWhere('passport_number','like',"%$s%")))->orderBy('name');return $this->page($q,$r);} public function customer(Customer $customer){return response()->json(['data'=>$customer->load(['building','room','plans.mealPlan','invoices'])]);}
 public function customerByQr(string $token){$customer=Customer::where('qr_token',$token)->firstOrFail();return response()->json(['data'=>$customer->load(['building','room','plans.mealPlan','invoices'])]);}
 public function buildingSummary(Building $building){$today=today();return response()->json(['data'=>['building'=>$building->only('uuid','name','code'),'total_workers'=>Customer::where('building_id',$building->id)->where('is_active',true)->count(),'active_meal_plans'=>MealPlan::whereHas('customerPlans.customer',fn($q)=>$q->where('building_id',$building->id)->where('is_active',true))->distinct()->count(),'meals_today'=>Delivery::whereHas('customer',fn($q)=>$q->where('building_id',$building->id))->whereDate('delivery_date',$today)->where('status','delivered')->sum('quantity'),'billed_amount'=>Invoice::whereHas('customer',fn($q)=>$q->where('building_id',$building->id))->whereBetween('period_start',[$today->copy()->startOfMonth(),$today->copy()->endOfMonth()])->sum('current_charges'),'received_amount'=>Payment::whereNull('reverses_payment_id')->whereHas('customer',fn($q)=>$q->where('building_id',$building->id))->whereBetween('paid_at',[$today->copy()->startOfMonth(),$today->copy()->endOfMonth()])->sum('amount'),'outstanding_balance'=>Invoice::whereHas('customer',fn($q)=>$q->where('building_id',$building->id))->sum('balance')]]);}
 public function deliveries(Request $r){return $this->page(Delivery::with('customer.room')->when($r->date,fn($q,$d)=>$q->whereDate('delivery_date',$d))->latest(),$r);}
 public function storeDelivery(Request $r){$d=$r->validate(['uuid'=>'required|uuid','customer_id'=>'required|uuid','delivery_date'=>'required|date','meal_option'=>'required|in:morning,evening','status'=>['required',Rule::enum(DeliveryStatus::class)],'quantity'=>'integer|min:1|max:20','notes'=>'nullable|string|max:500','idempotency_key'=>'required|string|max:190','record_version'=>'nullable|integer']);if($existing=Delivery::where('idempotency_key',$d['idempotency_key'])->first())return response()->json(['data'=>$existing]);$customer=Customer::where('uuid',$d['customer_id'])->firstOrFail();$delivery=Delivery::updateOrCreate(['customer_id'=>$customer->id,'delivery_date'=>$d['delivery_date'],'meal_option'=>$d['meal_option']],['uuid'=>$d['uuid'],'company_id'=>$r->user()->company_id,'status'=>$d['status'],'quantity'=>$d['quantity']??1,'notes'=>$d['notes']??null,'idempotency_key'=>$d['idempotency_key'],'recorded_by'=>$r->user()->id,'version'=>($d['record_version']??0)+1]);AuditService::record('delivery.recorded',$delivery);return response()->json(['data'=>$delivery],201);}
 public function invoices(Request $r){return $this->page(Invoice::with('customer')->latest(),$r);} public function createInvoice(Request $r,BillingService $billing){$d=$r->validate(['customer_id'=>'required|uuid','period_start'=>'required|date','period_end'=>'required|date|after_or_equal:period_start']);$customer=Customer::whereUuid($d['customer_id'])->firstOrFail();return response()->json(['data'=>$billing->generate($customer,now()->parse($d['period_start']),now()->parse($d['period_end']))],201);}
 public function payments(Request $r,PaymentService $service){$d=$r->validate(['invoice_id'=>'nullable|uuid','customer_id'=>'required_without:invoice_id|uuid','amount'=>'required|decimal:0,2|gt:0','mode'=>['required',Rule::enum(PaymentMode::class)],'paid_at'=>'nullable|date','reference'=>'nullable|string|max:100','notes'=>'nullable|string|max:500','idempotency_key'=>'required|string|max:190','record_version'=>'nullable|integer']);return response()->json(['data'=>$service->create($d,$r->user()->id)],201);}
 public function mealPlans(Request $r){return $this->page(MealPlan::orderBy('name'),$r);}
}
