<?php
namespace App\Http\Controllers\Api;
use App\Enums\{DeliveryStatus,Role}; use App\Http\Controllers\Controller; use App\Models\{Building,CashHandover,Customer,CustomerPlan,DailyClosing,Delivery,DeliveryChangeRequest,Device,MealPause,MealPlan,MealSkip,NotificationLog,Payment,PaymentCorrection,User}; use App\Services\{AuditService,CorrectionService}; use Illuminate\Http\Request; use Illuminate\Support\Arr; use Illuminate\Support\Facades\DB; use Illuminate\Support\Str; use Illuminate\Validation\Rule;
class WorkflowController extends Controller {
 private function cid(Request $r):int{return (int)$r->user()->company_id;}
 public function employees(Request $r){return response()->json(User::where('company_id',$this->cid($r))->with('buildings')->orderBy('name')->paginate(50));}
 public function storeEmployee(Request $r){$d=$r->validate(['name'=>'required|max:150','email'=>'required|email|unique:users,email','phone'=>'nullable|max:30','password'=>'required|min:12','role'=>['required',Rule::enum(Role::class)],'building_ids'=>'array','building_ids.*'=>'uuid']);abort_if($d['role']===Role::PlatformAdmin->value,422);$u=User::create([...Arr::except($d,'building_ids'),'company_id'=>$this->cid($r)]);$ids=Building::whereIn('uuid',$d['building_ids']??[])->pluck('id');$u->buildings()->syncWithPivotValues($ids,['company_id'=>$this->cid($r)]);AuditService::record('employee.created',$u);return response()->json(['data'=>$u->load('buildings')],201);}
 public function updateEmployee(Request $r,User $employee){abort_unless($employee->company_id===$this->cid($r),404);$d=$r->validate(['name'=>'sometimes|required|max:150','phone'=>'nullable|max:30','role'=>['sometimes',Rule::enum(Role::class)],'is_active'=>'sometimes|boolean','building_ids'=>'sometimes|array','building_ids.*'=>'uuid']);$employee->update(Arr::except($d,'building_ids'));if(isset($d['building_ids']))$employee->buildings()->syncWithPivotValues(Building::whereIn('uuid',$d['building_ids'])->pluck('id'),['company_id'=>$this->cid($r)]);AuditService::record('employee.updated',$employee);return response()->json(['data'=>$employee->load('buildings')]);}
 public function pause(Request $r,Customer $customer){$d=$r->validate(['starts_on'=>'required|date','resumes_on'=>'nullable|date|after:starts_on','reason'=>'nullable|max:500']);$p=MealPause::create([...$d,'customer_id'=>$customer->id,'created_by'=>$r->user()->id]);AuditService::record('meal.paused',$p);return response()->json(['data'=>$p],201);}
 public function bulkPause(Request $r){$d=$r->validate(['customer_ids'=>'required|array|min:1','customer_ids.*'=>'uuid','starts_on'=>'required|date','resumes_on'=>'nullable|date|after:starts_on','reason'=>'nullable|max:500']);$customers=Customer::whereIn('uuid',$d['customer_ids'])->get();foreach($customers as $c)MealPause::create(['customer_id'=>$c->id,'starts_on'=>$d['starts_on'],'resumes_on'=>$d['resumes_on']??null,'reason'=>$d['reason']??null,'created_by'=>$r->user()->id]);AuditService::record('meal.bulk_paused',null,[],['count'=>$customers->count()]);return response()->json(['data'=>['processed'=>$customers->count()]]);}
 public function bulkPlan(Request $r){$d=$r->validate(['customer_ids'=>'required|array|min:1','customer_ids.*'=>'uuid','meal_plan_id'=>'required|uuid','starts_on'=>'required|date','rate_override'=>'nullable|decimal:0,2|min:0']);$plan=MealPlan::whereUuid($d['meal_plan_id'])->firstOrFail();$customers=Customer::whereIn('uuid',$d['customer_ids'])->get();foreach($customers as $c)CustomerPlan::create(['customer_id'=>$c->id,'meal_plan_id'=>$plan->id,'starts_on'=>$d['starts_on'],'rate_override'=>$d['rate_override']??null]);AuditService::record('customer.bulk_plan_assigned',null,[],['count'=>$customers->count(),'plan'=>$plan->name]);return response()->json(['data'=>['processed'=>$customers->count()]]);}
 public function skip(Request $r,Customer $customer){$d=$r->validate(['skip_date'=>'required|date','meal_option'=>'required|in:morning,evening,both','reason'=>'nullable|max:500']);$s=MealSkip::updateOrCreate(['customer_id'=>$customer->id,'skip_date'=>$d['skip_date'],'meal_option'=>$d['meal_option']],[...$d,'company_id'=>$this->cid($r),'created_by'=>$r->user()->id]);AuditService::record('meal.skipped',$s);return response()->json(['data'=>$s],201);}
 public function bulkDelivery(Request $r){$d=$r->validate(['scope'=>'required|in:room,building,customers','scope_id'=>'required_unless:scope,customers|uuid','customer_ids'=>'required_if:scope,customers|array|min:1','customer_ids.*'=>'uuid','delivery_date'=>'required|date','meal_option'=>'required|in:morning,evening','status'=>['required',Rule::enum(DeliveryStatus::class)]]);$query=Customer::where('is_active',true);match($d['scope']){'room'=>$query->whereHas('room',fn($q)=>$q->whereUuid($d['scope_id'])),'building'=>$query->whereHas('building',fn($q)=>$q->whereUuid($d['scope_id'])),'customers'=>$query->whereIn('uuid',$d['customer_ids'])};$count=0;DB::transaction(function()use($query,$d,$r,&$count){$query->chunkById(200,function($customers)use($d,$r,&$count){foreach($customers as $c){$delivery=Delivery::where('customer_id',$c->id)->whereDate('delivery_date',$d['delivery_date'])->where('meal_option',$d['meal_option'])->first()??new Delivery(['customer_id'=>$c->id,'delivery_date'=>$d['delivery_date'],'meal_option'=>$d['meal_option']]);$delivery->fill(['company_id'=>$c->company_id,'status'=>$d['status'],'quantity'=>1,'recorded_by'=>$r->user()->id,'idempotency_key'=>$delivery->idempotency_key?:'bulk-'.Str::uuid(),'version'=>($delivery->version?:0)+1]);$delivery->save();$count++;}});});AuditService::record('delivery.bulk_recorded',null,[],['scope'=>$d['scope'],'count'=>$count]);return response()->json(['data'=>['processed'=>$count]]);}
 public function requestDeliveryChange(Request $r,Delivery $delivery){$d=$r->validate(['status'=>['required',Rule::enum(DeliveryStatus::class)],'quantity'=>'required|integer|min:1|max:20','reason'=>'required|string|min:5|max:1000']);$c=DeliveryChangeRequest::create(['delivery_id'=>$delivery->id,'requested_by'=>$r->user()->id,'requested_status'=>$d['status'],'requested_quantity'=>$d['quantity'],'reason'=>$d['reason'],'status'=>'pending']);$delivery->update(['requires_approval'=>true]);AuditService::record('delivery.change_requested',$c);return response()->json(['data'=>$c],201);}
 public function deliveryChanges(){return response()->json(DeliveryChangeRequest::with(['delivery.customer','requester'])->latest()->paginate(50));}
 public function reviewDeliveryChange(Request $r,DeliveryChangeRequest $change){$d=$r->validate(['decision'=>'required|in:approve,reject']);abort_if($change->status!=='pending',409,'Request already reviewed.');DB::transaction(function()use($change,$d,$r){$change->update(['status'=>$d['decision']==='approve'?'approved':'rejected','reviewed_by'=>$r->user()->id,'reviewed_at'=>now()]);if($d['decision']==='approve')$change->delivery->update(['status'=>$change->requested_status,'quantity'=>$change->requested_quantity,'requires_approval'=>false,'confirmed_by'=>$r->user()->id,'confirmed_at'=>now(),'version'=>$change->delivery->version+1]);else $change->delivery->update(['requires_approval'=>false]);});AuditService::record('delivery.change_reviewed',$change);return response()->json(['data'=>$change->fresh('delivery')]);}
 public function ledger(Customer $customer){return response()->json(['data'=>['customer'=>$customer->only('uuid','customer_code','name','masked_passport'),'entries'=>$customer->ledger()->with('source')->latest()->paginate(100)]]);}
 public function requestCorrection(Request $r,Payment $payment){$d=$r->validate(['corrected_amount'=>'nullable|decimal:0,2|gt:0','corrected_mode'=>'nullable|in:cash,card','reason'=>'required|string|min:5|max:1000']);$c=PaymentCorrection::create([...$d,'payment_id'=>$payment->id,'requested_by'=>$r->user()->id]);AuditService::record('payment.correction.requested',$c);return response()->json(['data'=>$c],201);}
 public function corrections(){return response()->json(PaymentCorrection::with(['payment.customer','requester'])->latest()->paginate(50));}
 public function reviewCorrection(Request $r,PaymentCorrection $correction,CorrectionService $service){$d=$r->validate(['decision'=>'required|in:approve,reject','review_notes'=>'nullable|max:1000']);if($d['decision']==='reject'){$correction->update(['status'=>'rejected','reviewed_by'=>$r->user()->id,'reviewed_at'=>now(),'review_notes'=>$d['review_notes']??null]);return response()->json(['data'=>$correction]);}return response()->json(['data'=>$service->approve($correction,$r->user()->id)]);}
 public function closeDay(Request $r){$date=$r->date('closing_date')??today();$cash=(float)Payment::where('employee_id',$r->user()->id)->whereDate('paid_at',$date)->where('mode','cash')->sum('amount');$card=(float)Payment::where('employee_id',$r->user()->id)->whereDate('paid_at',$date)->where('mode','card')->sum('amount');$receipts=Payment::where('employee_id',$r->user()->id)->whereDate('paid_at',$date)->count();$submitted=(float)CashHandover::where('employee_id',$r->user()->id)->whereDate('submitted_at',$date)->sum('amount_submitted');$c=DailyClosing::updateOrCreate(['company_id'=>$this->cid($r),'employee_id'=>$r->user()->id,'closing_date'=>$date],['cash_total'=>$cash,'card_total'=>$card,'receipt_count'=>$receipts,'cash_submitted'=>$submitted,'pending_cash'=>$cash-$submitted,'variance'=>0,'notes'=>$r->input('notes'),'closed_at'=>now()]);return response()->json(['data'=>$c],201);}
 public function notifications(Request $r){return response()->json(NotificationLog::where(fn($q)=>$q->where('user_id',$r->user()->id)->orWhereNull('user_id'))->latest()->paginate(50));}
 public function announce(Request $r){$d=$r->validate(['subject'=>'required|max:150','message'=>'required|max:1000']);$log=NotificationLog::create(['company_id'=>$this->cid($r),'type'=>'announcement','channel'=>'in_app','subject'=>$d['subject'],'message'=>$d['message'],'status'=>'sent','sent_at'=>now()]);AuditService::record('notification.announced',$log);return response()->json(['data'=>$log],201);}
 public function readNotification(Request $r,NotificationLog $notification){$notification->update(['read_at'=>now()]);return response()->noContent();}
 public function devices(){return response()->json(Device::with('user')->latest()->paginate(50));}
 public function deviceStatus(Request $r,Device $device){$d=$r->validate(['action'=>'required|in:approve,disable']);$device->update($d['action']==='approve'?['approved_at'=>now(),'disabled_at'=>null]:['disabled_at'=>now()]);return response()->json(['data'=>$device]);}
 public function settings(Request $r){return response()->json(['data'=>$r->user()->company]);}
 public function updateSettings(Request $r){$d=$r->validate(['currency'=>'sometimes|string|size:3','timezone'=>'sometimes|string|max:60','delivery_cutoff_time'=>'sometimes|date_format:H:i','invoice_due_days'=>'sometimes|integer|min:0|max:365','receipt_prefix'=>'nullable|max:20','locale'=>'sometimes|in:en,ur,ar','low_balance_threshold'=>'nullable|decimal:0,2|min:0','settings'=>'nullable|array']);$r->user()->company->update($d);return response()->json(['data'=>$r->user()->company->fresh()]);}
}
