<x-layouts.app :title="$title"><section class="panel"><div class="panel-head"><h2>{{ $title }}</h2><button type="button" onclick="document.getElementById('create').showModal()">Add new</button></div><div class="table-wrap"><table><thead><tr>@foreach($columns as $column)<th>{{ str_replace(['.','_'],' ',ucfirst($column)) }}</th>@endforeach@if(in_array($create,['buildings','rooms','customers','plans','employees']))<th>Actions</th>@endif</tr></thead><tbody>@forelse($rows as $row)<tr>@foreach($columns as $column)<td>@php($value=data_get($row,$column))@if($value instanceof \BackedEnum){{ str_replace('_',' ',$value->value) }}@elseif(is_bool($value))<span class="badge">{{ $value?'Active':'Inactive' }}</span>@else{{ $value }}@endif</td>@endforeach
@if($create==='buildings')<td><button type="button" onclick='openEdit("{{ url("buildings/".$row->uuid) }}",@json(["name"=>$row->name,"code"=>$row->code,"address"=>$row->address,"contact_person"=>$row->contact_person,"is_active"=>$row->is_active])) '>Edit</button></td>
@elseif($create==='rooms')<td><button type="button" onclick='openEdit("{{ url("rooms/".$row->uuid) }}",@json(["number"=>$row->number,"floor"=>$row->floor,"capacity"=>$row->capacity,"delivery_enabled"=>$row->delivery_enabled])) '>Edit</button></td>
@elseif($create==='customers')<td><button type="button" onclick='openEdit("{{ url("customers/".$row->uuid) }}",@json(["name"=>$row->name,"phone"=>$row->phone,"room_id"=>$row->room_id,"is_active"=>$row->is_active])) '>Edit</button></td>
@elseif($create==='plans')<td><button type="button" onclick='openEdit("{{ url("meal-plans/".$row->uuid) }}",@json(["name"=>$row->name,"daily_rate"=>$row->daily_rate,"monthly_rate"=>$row->monthly_rate,"is_active"=>$row->is_active])) '>Edit</button></td>
@elseif($create==='employees')<td><form method="post" action="{{ url('employees/'.$row->uuid.'/toggle') }}">@csrf<button type="submit">{{ $row->is_active?'Disable':'Enable' }}</button></form></td>
@endif
</tr>@empty<tr><td colspan="{{count($columns)+1}}">No records yet.</td></tr>@endforelse</tbody></table></div>{{ $rows->withQueryString()->links() }}</section>

<dialog id="create"><form method="post">@csrf<div class="panel-head"><h2>Add {{ str($create)->singular()->replace('-',' ')->title() }}</h2><button class="close" type="button" onclick="this.closest('dialog').close()">×</button></div>
@if($create==='companies')<label>Company name<input name="name" required></label><label>Code<input name="code" required></label><label>Admin name<input name="admin_name" required></label><label>Admin email<input type="email" name="admin_email" required></label><label>Temporary password<input type="password" name="password" minlength="12" required></label>
@elseif($create==='buildings')<label>Name<input name="name" required></label><label>Code<input name="code" required></label><label>Address<textarea name="address"></textarea></label>
@elseif($create==='rooms')<label>Building<select name="building_id">@foreach($buildings as $building)<option value="{{$building->id}}">{{$building->name}}</option>@endforeach</select></label><label>Room number<input name="number" required></label><label>Floor<input name="floor"></label><label>Capacity<input type="number" name="capacity" min="1" value="4" required></label>
@elseif($create==='customers')<label>Customer code<input name="customer_code" required></label><label>Full name<input name="name" required></label><label>Passport number<input name="passport_number" required></label><label>Phone<input name="phone"></label><label>Building<select name="building_id">@foreach($buildings as $building)<option value="{{$building->id}}">{{$building->name}}</option>@endforeach</select></label><label>Room<select name="room_id">@foreach($rooms as $room)<option value="{{$room->id}}">{{$room->building->name??''}} / {{$room->number}}</option>@endforeach</select></label><label>Start date<input type="date" name="start_date" value="{{today()->format('Y-m-d')}}" required></label><label>Opening balance<input type="number" step="0.01" name="opening_balance" value="0"></label>
@elseif($create==='employees')<label>Name<input name="name" required></label><label>Email<input type="email" name="email" required></label><label>Phone<input name="phone"></label><label>Temporary password<input type="password" name="password" minlength="12" required></label><label>Role<select name="role"><option value="company_admin">Company admin</option><option value="supervisor">Supervisor</option><option value="collection_employee">Collection employee</option><option value="delivery_employee">Delivery employee</option></select></label>@foreach($buildings as $building)<label class="check"><input type="checkbox" name="building_ids[]" value="{{$building->id}}"> {{$building->name}}</label>@endforeach
@else<label>Name<input name="name" required></label><label>Meal option<select name="meal_option"><option value="morning">Morning</option><option value="evening">Evening</option><option value="both">Both</option></select></label><label>Billing type<select name="billing_type"><option value="fixed_monthly">Fixed monthly</option><option value="delivered_daily">Delivered daily</option></select></label><label>Daily rate<input type="number" step="0.01" name="daily_rate" value="0"></label><label>Monthly rate<input type="number" step="0.01" name="monthly_rate" value="0"></label><label class="check"><input type="checkbox" name="credit_pauses" value="1"> Credit pauses</label><label class="check"><input type="checkbox" name="credit_skips" value="1"> Credit skips</label>
@endif
<button type="submit">Save record</button></form></dialog>

@if(in_array($create,['buildings','rooms','customers','plans']))
<dialog id="edit"><form method="post" id="editForm">@csrf<div class="panel-head"><h2>Edit {{ str($create)->singular()->replace('-',' ')->title() }}</h2><button class="close" type="button" onclick="this.closest('dialog').close()">×</button></div>
@if($create==='buildings')<label>Name<input name="name" id="e_name" required></label><label>Code<input name="code" id="e_code" required></label><label>Address<textarea name="address" id="e_address"></textarea></label><label>Contact person<input name="contact_person" id="e_contact_person"></label><label class="check"><input type="checkbox" name="is_active" id="e_is_active" value="1"> Active</label>
@elseif($create==='rooms')<label>Room number<input name="number" id="e_number" required></label><label>Floor<input name="floor" id="e_floor"></label><label>Capacity<input type="number" name="capacity" id="e_capacity" min="1" required></label><label class="check"><input type="checkbox" name="delivery_enabled" id="e_delivery_enabled" value="1"> Delivery enabled</label>
@elseif($create==='customers')<label>Full name<input name="name" id="e_name" required></label><label>Phone<input name="phone" id="e_phone"></label><label>Room<select name="room_id" id="e_room_id">@foreach($rooms as $room)<option value="{{$room->id}}">{{$room->building->name??''}} / {{$room->number}}</option>@endforeach</select></label><label class="check"><input type="checkbox" name="is_active" id="e_is_active" value="1"> Active</label>
@elseif($create==='plans')<label>Name<input name="name" id="e_name" required></label><label>Daily rate<input type="number" step="0.01" name="daily_rate" id="e_daily_rate"></label><label>Monthly rate<input type="number" step="0.01" name="monthly_rate" id="e_monthly_rate"></label><label class="check"><input type="checkbox" name="is_active" id="e_is_active" value="1"> Active</label>
@endif
<button type="submit">Save changes</button></form></dialog>
<script>function openEdit(action,fields){var f=document.getElementById('editForm');f.action=action;for(var k in fields){var el=document.getElementById('e_'+k);if(!el)continue;if(el.type==='checkbox'){el.checked=!!Number(fields[k]);}else{el.value=fields[k]===null?'':fields[k];}}document.getElementById('edit').showModal();}</script>
@endif
</x-layouts.app>
