<x-layouts.app :title="$title"><section class="panel"><div class="panel-head"><h2>{{$title}}</h2></div><div class="table-wrap"><table><thead><tr>@foreach($columns as $column)<th>{{str_replace(['.','_'],' ',ucfirst($column))}}</th>@endforeach@if(in_array($title,['Invoices','Payments','Cash handovers','Payment corrections','Delivery change requests']))<th>Actions</th>@endif</tr></thead><tbody>@forelse($rows as $row)<tr>@foreach($columns as $column)<td>@php($value=data_get($row,$column))@if($value instanceof BackedEnum){{str_replace('_',' ',$value->value)}}@elseif($value instanceof DateTimeInterface){{$value->format('d M Y H:i')}}@elseif(is_bool($value))<span class="badge">{{$value?'Active':'Inactive'}}</span>@else{{$value}}@endif</td>@endforeach
@if($title==='Invoices')<td><a href="{{ url('invoices/'.$row->uuid.'/pdf') }}">Download PDF</a></td>
@elseif($title==='Payments')<td>@if($row->receipt)<a href="{{ url('receipts/'.$row->receipt->uuid.'/pdf') }}">Download receipt</a>@endif</td>
@elseif($title==='Cash handovers')<td>@if(in_array($row->status->value,['not_submitted','partially_submitted','submitted']))<button type="button" onclick='openVerify("{{ url("cash-handovers/".$row->uuid."/verify") }}",{{ $row->amount_submitted }})'>Verify</button>@endif</td>
@elseif($title==='Payment corrections')<td>@if($row->status==='pending')<form method="post" action="{{ url('payment-corrections/'.$row->uuid) }}" style="display:inline">@csrf<input type="hidden" name="decision" value="approve"><button type="submit">Approve</button></form> <form method="post" action="{{ url('payment-corrections/'.$row->uuid) }}" style="display:inline">@csrf<input type="hidden" name="decision" value="reject"><button type="submit">Reject</button></form>@endif</td>
@elseif($title==='Delivery change requests')<td>@if($row->status==='pending')<form method="post" action="{{ url('delivery-change-requests/'.$row->uuid) }}" style="display:inline">@csrf<input type="hidden" name="decision" value="approve"><button type="submit">Approve</button></form> <form method="post" action="{{ url('delivery-change-requests/'.$row->uuid) }}" style="display:inline">@csrf<input type="hidden" name="decision" value="reject"><button type="submit">Reject</button></form>@endif</td>
@endif
</tr>@empty<tr><td colspan="{{count($columns)+(in_array($title,['Invoices','Payments','Cash handovers','Payment corrections','Delivery change requests'])?1:0)}}">No records found.</td></tr>@endforelse</tbody></table></div>{{$rows->withQueryString()->links()}}</section>
@if($title==='Cash handovers')
<dialog id="verify"><form method="post" id="verifyForm">@csrf<div class="panel-head"><h2>Verify cash handover</h2><button class="close" type="button" onclick="this.closest('dialog').close()">×</button></div><label>Verified amount<input type="number" step="0.01" min="0" name="verified_amount" id="v_amount" required></label><label>Decision<select name="status"><option value="verified">Verified</option><option value="rejected">Rejected</option></select></label><button type="submit">Save</button></form></dialog>
<script>function openVerify(action,amount){document.getElementById('verifyForm').action=action;document.getElementById('v_amount').value=amount;document.getElementById('verify').showModal();}</script>
@endif
</x-layouts.app>
