<?php
use App\Http\Controllers\Api\{AuthController,FinanceController,ImportController,OperationsController,WorkflowController}; use App\Http\Controllers\ReportController; use Illuminate\Support\Facades\Route;
Route::prefix('v1')->group(function(){Route::post('auth/login',[AuthController::class,'login'])->middleware('throttle:5,1');Route::middleware(['auth:sanctum','active','throttle:120,1'])->group(function(){
 Route::get('me',[AuthController::class,'me']);Route::post('auth/logout',[AuthController::class,'logout']);Route::post('devices',[AuthController::class,'registerDevice']);
 Route::get('buildings',[OperationsController::class,'buildings']);Route::get('buildings/{building}/summary',[OperationsController::class,'buildingSummary']);Route::get('rooms',[OperationsController::class,'rooms']);Route::get('customers',[OperationsController::class,'customers']);Route::get('customers/qr/{token}',[OperationsController::class,'customerByQr']);Route::get('customers/{customer}',[OperationsController::class,'customer']);Route::get('customers/{customer}/receipts',[FinanceController::class,'customerReceipts']);Route::get('meal-plans',[OperationsController::class,'mealPlans']);
 Route::get('deliveries',[OperationsController::class,'deliveries']);Route::post('deliveries',[OperationsController::class,'storeDelivery'])->middleware('role:platform_admin,company_admin,supervisor,delivery_employee');
 Route::get('invoices',[OperationsController::class,'invoices']);Route::post('invoices',[OperationsController::class,'createInvoice'])->middleware('role:platform_admin,company_admin,supervisor');Route::post('payments',[OperationsController::class,'payments'])->middleware('role:platform_admin,company_admin,supervisor,collection_employee');
 Route::get('collections',[FinanceController::class,'collections']);Route::get('cash-handovers',[FinanceController::class,'handovers']);Route::post('cash-handovers',[FinanceController::class,'storeHandover']);Route::patch('cash-handovers/{handover}/verify',[FinanceController::class,'verify'])->middleware('role:platform_admin,company_admin,supervisor');
 Route::post('payments/{payment}/proof',[FinanceController::class,'paymentProof']);Route::post('cash-handovers/{handover}/proof',[FinanceController::class,'handoverProof']);Route::get('proofs/{type}/{uuid}',[FinanceController::class,'proof'])->whereIn('type',['payment','handover']);
 Route::get('receipts/{receipt}/pdf',[FinanceController::class,'receipt'])->name('receipts.pdf');Route::post('receipts/{receipt}/share',[FinanceController::class,'share']);
 Route::get('employees',[WorkflowController::class,'employees'])->middleware('role:company_admin,supervisor');Route::post('employees',[WorkflowController::class,'storeEmployee'])->middleware('role:company_admin');Route::patch('employees/{employee}',[WorkflowController::class,'updateEmployee'])->middleware('role:company_admin');
 Route::post('customers/{customer}/pauses',[WorkflowController::class,'pause']);Route::post('customers/bulk-pause',[WorkflowController::class,'bulkPause'])->middleware('role:company_admin,supervisor');Route::post('customers/bulk-plan',[WorkflowController::class,'bulkPlan'])->middleware('role:company_admin,supervisor');Route::post('customers/{customer}/skips',[WorkflowController::class,'skip']);Route::get('customers/{customer}/ledger',[WorkflowController::class,'ledger']);Route::post('deliveries/bulk',[WorkflowController::class,'bulkDelivery'])->middleware('role:company_admin,supervisor,delivery_employee');
 Route::post('deliveries/{delivery}/change-requests',[WorkflowController::class,'requestDeliveryChange']);Route::get('delivery-change-requests',[WorkflowController::class,'deliveryChanges'])->middleware('role:company_admin,supervisor');Route::patch('delivery-change-requests/{change}',[WorkflowController::class,'reviewDeliveryChange'])->middleware('role:company_admin,supervisor');
 Route::post('payments/{payment}/corrections',[WorkflowController::class,'requestCorrection']);Route::get('payment-corrections',[WorkflowController::class,'corrections'])->middleware('role:company_admin,supervisor');Route::patch('payment-corrections/{correction}',[WorkflowController::class,'reviewCorrection'])->middleware('role:company_admin,supervisor');Route::post('daily-closings',[WorkflowController::class,'closeDay']);
 Route::get('notifications',[WorkflowController::class,'notifications']);Route::patch('notifications/{notification}/read',[WorkflowController::class,'readNotification']);Route::post('notifications/announce',[WorkflowController::class,'announce'])->middleware('role:platform_admin,company_admin,supervisor');Route::get('devices',[WorkflowController::class,'devices'])->middleware('role:company_admin,supervisor');Route::patch('devices/{device}',[WorkflowController::class,'deviceStatus'])->middleware('role:company_admin');
 Route::get('settings',[WorkflowController::class,'settings']);Route::put('settings',[WorkflowController::class,'updateSettings'])->middleware('role:company_admin');Route::get('reports/{report}',[ReportController::class,'data'])->middleware('role:company_admin,supervisor');
 Route::get('imports',[ImportController::class,'index'])->middleware('role:company_admin,supervisor');Route::post('imports',[ImportController::class,'store'])->middleware('role:company_admin,supervisor');
});});
