<?php
namespace Tests\Feature;
use App\Enums\{InvoiceStatus,PaymentMode,Role}; use App\Models\{Building,Company,Customer,Invoice,Payment,Room,User}; use Illuminate\Foundation\Testing\RefreshDatabase; use Illuminate\Support\Str; use Laravel\Sanctum\Sanctum; use Tests\TestCase;
class OperationalWorkflowTest extends TestCase { use RefreshDatabase;
 private function setupTenant():array{$company=Company::create(['name'=>'Operations Co','code'=>'OPS']);$admin=User::factory()->create(['company_id'=>$company->id,'role'=>Role::CompanyAdmin]);$building=Building::withoutGlobalScopes()->create(['company_id'=>$company->id,'name'=>'Camp','code'=>'CAMP']);$room=Room::withoutGlobalScopes()->create(['company_id'=>$company->id,'building_id'=>$building->id,'number'=>'10','capacity'=>5]);$customer=Customer::withoutGlobalScopes()->create(['company_id'=>$company->id,'building_id'=>$building->id,'room_id'=>$room->id,'customer_code'=>'W1','name'=>'Worker One','passport_number'=>'PX1','start_date'=>today()]);return compact('company','admin','building','room','customer');}
 public function test_admin_can_create_employee_with_building_assignment():void{$x=$this->setupTenant();Sanctum::actingAs($x['admin']);$this->postJson('/api/v1/employees',['name'=>'Driver','email'=>'driver@example.test','password'=>'VeryStrong!123','role'=>'delivery_employee','building_ids'=>[$x['building']->uuid]])->assertCreated()->assertJsonPath('data.buildings.0.uuid',$x['building']->uuid);$this->assertDatabaseHas('building_user',['building_id'=>$x['building']->id]);}
 public function test_room_bulk_delivery_is_idempotent_per_customer_and_meal():void{$x=$this->setupTenant();Sanctum::actingAs($x['admin']);$payload=['scope'=>'room','scope_id'=>$x['room']->uuid,'delivery_date'=>today()->format('Y-m-d'),'meal_option'=>'morning','status'=>'delivered'];$this->postJson('/api/v1/deliveries/bulk',$payload)->assertOk()->assertJsonPath('data.processed',1);$this->postJson('/api/v1/deliveries/bulk',[...$payload,'status'=>'not_delivered'])->assertOk();$this->assertDatabaseCount('deliveries',1);$this->assertDatabaseHas('deliveries',['customer_id'=>$x['customer']->id,'status'=>'not_delivered','version'=>2]);}
 public function test_payment_correction_creates_reversal_and_replacement():void{$x=$this->setupTenant();$invoice=Invoice::withoutGlobalScopes()->create(['company_id'=>$x['company']->id,'customer_id'=>$x['customer']->id,'invoice_number'=>'OPS-I1','period_start'=>today()->startOfMonth(),'period_end'=>today()->endOfMonth(),'current_charges'=>100,'total_payable'=>100,'amount_paid'=>100,'balance'=>0,'status'=>InvoiceStatus::FullyPaid]);$payment=Payment::withoutGlobalScopes()->create(['company_id'=>$x['company']->id,'customer_id'=>$x['customer']->id,'invoice_id'=>$invoice->id,'employee_id'=>$x['admin']->id,'amount'=>100,'mode'=>PaymentMode::Cash,'paid_at'=>now(),'idempotency_key'=>'original']);Sanctum::actingAs($x['admin']);$uuid=$this->postJson('/api/v1/payments/'.$payment->uuid.'/corrections',['corrected_amount'=>80,'corrected_mode'=>'card','reason'=>'Customer paid AED 80 by card'])->assertCreated()->json('data.uuid');$this->patchJson('/api/v1/payment-corrections/'.$uuid,['decision'=>'approve'])->assertOk();$this->assertDatabaseHas('invoices',['id'=>$invoice->id,'amount_paid'=>80,'balance'=>20,'status'=>'partially_paid']);$this->assertDatabaseCount('payments',3);}
 public function test_reports_and_company_settings_are_available():void{$x=$this->setupTenant();Sanctum::actingAs($x['admin']);$this->putJson('/api/v1/settings',['currency'=>'AED','timezone'=>'Asia/Dubai','delivery_cutoff_time'=>'21:30','invoice_due_days'=>10])->assertOk()->assertJsonPath('data.invoice_due_days',10);$this->getJson('/api/v1/reports/outstanding')->assertOk()->assertJsonPath('data.head.0','Customer');}
}
