<?php
namespace Tests\Feature;
use App\Enums\{InvoiceStatus,PaymentMode,Role}; use App\Models\{Building,Company,Customer,Invoice,Room,User}; use Illuminate\Foundation\Testing\RefreshDatabase; use Illuminate\Support\Str; use Laravel\Sanctum\Sanctum; use Tests\TestCase;
class TenantAndFinanceTest extends TestCase { use RefreshDatabase;
 private function tenant(string $code):array{$company=Company::create(['name'=>$code,'code'=>$code]);$user=User::factory()->create(['company_id'=>$company->id,'role'=>Role::CompanyAdmin]);return[$company,$user];}
 public function test_api_never_lists_another_company_building():void{[$a,$user]=$this->tenant('ONE');[$b]=$this->tenant('TWO');Building::withoutGlobalScopes()->create(['company_id'=>$a->id,'name'=>'Visible','code'=>'V']);Building::withoutGlobalScopes()->create(['company_id'=>$b->id,'name'=>'Hidden','code'=>'H']);Sanctum::actingAs($user);$this->getJson('/api/v1/buildings')->assertOk()->assertJsonCount(1,'data')->assertJsonPath('data.0.name','Visible');}
 public function test_offline_delivery_retry_is_idempotent():void{[$company,$user]=$this->tenant('IDEM');$building=Building::withoutGlobalScopes()->create(['company_id'=>$company->id,'name'=>'B','code'=>'B']);$room=Room::withoutGlobalScopes()->create(['company_id'=>$company->id,'building_id'=>$building->id,'number'=>'1','capacity'=>2]);$customer=Customer::withoutGlobalScopes()->create(['company_id'=>$company->id,'building_id'=>$building->id,'room_id'=>$room->id,'customer_code'=>'C1','name'=>'Worker','passport_number'=>'P1','start_date'=>today()]);Sanctum::actingAs($user);$payload=['uuid'=>(string)Str::uuid(),'customer_id'=>$customer->uuid,'delivery_date'=>today()->format('Y-m-d'),'meal_option'=>'morning','status'=>'delivered','idempotency_key'=>'device-1-event-1'];$this->postJson('/api/v1/deliveries',$payload)->assertCreated();$this->postJson('/api/v1/deliveries',[...$payload,'uuid'=>(string)Str::uuid()])->assertOk();$this->assertDatabaseCount('deliveries',1);}
 public function test_payment_updates_invoice_ledger_and_creates_receipt():void{[$company,$user]=$this->tenant('PAY');$building=Building::withoutGlobalScopes()->create(['company_id'=>$company->id,'name'=>'B','code'=>'B']);$room=Room::withoutGlobalScopes()->create(['company_id'=>$company->id,'building_id'=>$building->id,'number'=>'1','capacity'=>2]);$customer=Customer::withoutGlobalScopes()->create(['company_id'=>$company->id,'building_id'=>$building->id,'room_id'=>$room->id,'customer_code'=>'C1','name'=>'Worker','passport_number'=>'P1','start_date'=>today()]);$invoice=Invoice::withoutGlobalScopes()->create(['company_id'=>$company->id,'customer_id'=>$customer->id,'invoice_number'=>'I-1','period_start'=>today()->startOfMonth(),'period_end'=>today()->endOfMonth(),'current_charges'=>100,'total_payable'=>100,'balance'=>100,'status'=>InvoiceStatus::Unpaid]);Sanctum::actingAs($user);$this->postJson('/api/v1/payments',['invoice_id'=>$invoice->uuid,'amount'=>'100.00','mode'=>PaymentMode::Cash->value,'idempotency_key'=>'pay-1','record_version'=>1])->assertCreated()->assertJsonPath('data.receipt.receipt_number','PAY-R-0000001');$this->assertDatabaseHas('invoices',['id'=>$invoice->id,'balance'=>0,'status'=>'fully_paid']);$this->assertDatabaseHas('ledger_entries',['customer_id'=>$customer->id,'credit'=>100]);$this->assertDatabaseCount('receipts',1);}
}
