<?php

if (!function_exists('asset_path')) {
	/**
	 * Use the manifest.json generated by webpack-encore to find the
	 * paths for assets
	 *
	 * @param string $asset
	 *
	 * @return string
	 */
    function asset_path (string $asset) {
	    /** @var \Symfony\Component\Asset\Package $package */
	    $package = app("asset");

	    return $package->getUrl($asset);
    }
}
