<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up():void{
  Schema::table('companies',fn(Blueprint $t)=>[$t->json('settings')->nullable(),$t->string('receipt_prefix')->nullable(),$t->unsignedInteger('invoice_due_days')->default(7)]);
  Schema::table('users',fn(Blueprint $t)=>[$t->string('phone')->nullable(),$t->timestamp('last_login_at')->nullable()]);
  Schema::table('customers',fn(Blueprint $t)=>[$t->uuid('qr_token')->nullable()->unique(),$t->date('deactivated_at')->nullable()]);
  Schema::table('deliveries',function(Blueprint $t){$t->timestamp('confirmed_at')->nullable();$t->foreignId('confirmed_by')->nullable()->constrained('users')->nullOnDelete();$t->boolean('requires_approval')->default(false);});
  Schema::table('invoices',fn(Blueprint $t)=>[$t->date('due_date')->nullable(),$t->timestamp('issued_at')->nullable()]);
  Schema::create('building_user',function(Blueprint $t){$t->id();$t->foreignId('company_id')->constrained()->cascadeOnDelete();$t->foreignId('building_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->timestamps();$t->unique(['building_id','user_id']);});
  Schema::create('payment_corrections',function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->foreignId('company_id')->constrained()->cascadeOnDelete();$t->foreignId('payment_id')->constrained()->restrictOnDelete();$t->foreignId('requested_by')->constrained('users');$t->decimal('corrected_amount',12,2)->nullable();$t->string('corrected_mode')->nullable();$t->text('reason');$t->string('status')->default('pending');$t->foreignId('reviewed_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('reviewed_at')->nullable();$t->text('review_notes')->nullable();$t->timestamps();});
  Schema::create('delivery_change_requests',function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->foreignId('company_id')->constrained()->cascadeOnDelete();$t->foreignId('delivery_id')->constrained()->restrictOnDelete();$t->foreignId('requested_by')->constrained('users');$t->string('requested_status');$t->unsignedInteger('requested_quantity')->default(1);$t->text('reason');$t->string('status')->default('pending');$t->foreignId('reviewed_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('reviewed_at')->nullable();$t->timestamps();});
  Schema::create('daily_closings',function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->foreignId('company_id')->constrained()->cascadeOnDelete();$t->foreignId('employee_id')->constrained('users');$t->date('closing_date');$t->decimal('cash_total',12,2);$t->decimal('card_total',12,2);$t->unsignedInteger('receipt_count');$t->decimal('cash_submitted',12,2)->default(0);$t->decimal('pending_cash',12,2)->default(0);$t->decimal('variance',12,2)->default(0);$t->text('notes')->nullable();$t->timestamp('closed_at');$t->timestamps();$t->unique(['company_id','employee_id','closing_date']);});
  Schema::create('notification_logs',function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->foreignId('company_id')->constrained()->cascadeOnDelete();$t->foreignId('customer_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('user_id')->nullable()->constrained()->nullOnDelete();$t->string('type');$t->string('channel')->default('in_app');$t->string('recipient')->nullable();$t->string('subject');$t->text('message');$t->string('status')->default('pending');$t->timestamp('sent_at')->nullable();$t->timestamp('read_at')->nullable();$t->json('metadata')->nullable();$t->timestamps();});
  Schema::create('import_batches',function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->foreignId('company_id')->constrained()->cascadeOnDelete();$t->foreignId('uploaded_by')->constrained('users');$t->string('type');$t->string('filename');$t->unsignedInteger('total_rows')->default(0);$t->unsignedInteger('successful_rows')->default(0);$t->unsignedInteger('failed_rows')->default(0);$t->json('errors')->nullable();$t->string('status')->default('pending');$t->timestamps();});
 }
 public function down():void{foreach(['import_batches','notification_logs','daily_closings','delivery_change_requests','payment_corrections','building_user'] as $x)Schema::dropIfExists($x);}
};
