<?php

return array(

	/*
	|--------------------------------------------------------------------------
	| Additional Compiled Classes
	|--------------------------------------------------------------------------
	|
	| Here you may specify additional classes to include in the compiled file
	| generated by the `artisan optimize` command. These should be classes
	| that are included on basically every request into the application.
	|
	*/

	'files' => array(

		__DIR__.'/../providers/AppServiceProvider.php',
		__DIR__.'/../providers/ArtisanServiceProvider.php',
		__DIR__.'/../providers/ErrorServiceProvider.php',
		__DIR__.'/../providers/EventServiceProvider.php',
		__DIR__.'/../providers/FilterServiceProvider.php',
		__DIR__.'/../providers/LogServiceProvider.php',
		__DIR__.'/../providers/RouteServiceProvider.php',

	),

	/*
	|--------------------------------------------------------------------------
	| Compiled File Providers
	|--------------------------------------------------------------------------
	|
	| Here you may list service providers which define a "compiles" function
	| that returns additional files that should be compiled, providing an
	| easy way to get common files from any packages you are utilizing.
	|
	*/

	'providers' => array(
		//
	),

);
