<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Default namespaces for the classes generated via the make command
    |--------------------------------------------------------------------------
    |
    | You can change the default namespaces for the classes generated by the
    | make commands. All namespaces here will be relative to the root
    | application namespace and should start with a '\'.
    |
    | Current available keys are: console-command, controller, event, job,
    | listener, mail, middleware, model, notification, policy, provider,
    | request, seeder, test, viewcomposer.
    */

    'namespaces' => [
        // 'model' => '\Models',
        // 'viewcomposer' => '\ViewComposers',
    ],

];
