#!/usr/bin/env bash

# Purpose:
#
# Checks to see you have a recent version of Docker & Docker composer installed.

set -e

cd "$(dirname "$0")/.."

MINIMUM_DOCKER_VERSION=1.12
MINIMUM_DOCKER_COMPOSE_VERSION=1

function executableCheck {
    local EXE=$1
    local NAME=$2
    if [ "$EXE" == "0" ]; then
        echo No \"${NAME}\" command found
        exit 1
    else
        echo \"${NAME}\" command found
    fi

    # check if the command is executable
    if [ ! -e ${EXE} ]; then
        echo Docker installed but not executable
    fi
}

function versionCheck {
    local VERSION=$1
    local MINIMUM=$2
    local SYSTEM=$3
    local CHECK=`echo "$VERSION>=$MINIMUM" | bc -l`
    if [ "$CHECK" == "0" ]; then
        echo ${SYSTEM} version mismatch, please upgrade ${SYSTEM}
        exit 1
    else
        echo ${SYSTEM} version OK
    fi
}

echo "--> Checking Docker version"

# validate Docker command and version
DOCKER_EXE=$(/usr/bin/which docker || echo 0)
executableCheck ${DOCKER_EXE} "docker"

DOCKER_VERSION=$(${DOCKER_EXE} --version | cut -f 3 -d' ' | cut -f 1,2 -d '.');
versionCheck ${DOCKER_VERSION} ${MINIMUM_DOCKER_VERSION} "Docker"

# validate docker-compose command and version
DOCKER_COMPOSE_EXE=$(/usr/bin/which docker-compose || echo 0)
executableCheck ${DOCKER_COMPOSE_EXE} "docker-compose"

DOCKER_COMPOSE_VERSION="$(${DOCKER_COMPOSE_EXE} --version | cut -f 3 -d' ' | cut -f 1,2 -d '.')";
versionCheck ${DOCKER_COMPOSE_VERSION} ${MINIMUM_DOCKER_COMPOSE_VERSION} "Docker Compose"
