import os
import json
import subprocess
import requests

GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")
REPO = os.getenv("GITHUB_REPOSITORY")  # e.g. mmezzawi-intervu-ai/laravel
HEAD_BRANCH = "ai-fix-" + os.environ.get("GITHUB_RUN_ID", "temp")

def create_branch():
    subprocess.run(["git", "checkout", "-b", HEAD_BRANCH], check=True)

def apply_ai_fix():
    with open("output/review.json") as f:
        review = json.load(f)["review"]

    if "diff --git" not in review:
        print("No valid diff patch found. Skipping fix commit.")
        return False

    with open("ai_patch.diff", "w") as f:
        f.write(review)

    try:
        subprocess.run(["git", "apply", "ai_patch.diff"], check=True)
        subprocess.run(["git", "add", "."], check=True)
        subprocess.run(["git", "commit", "-m", "AI suggested fixes"], check=True)
        subprocess.run(["git", "push", "origin", HEAD_BRANCH], check=True)
        return True
    except subprocess.CalledProcessError:
        print("❌ Failed to apply AI patch.")
        return False

def create_pr():
    url = f"https://api.github.com/repos/{REPO}/pulls"
    data = {
        "title": "AI Suggested Fixes",
        "head": HEAD_BRANCH,
        "base": "main",
        "body": "Automated PR with fixes generated by AI review."
    }
    headers = {"Authorization": f"Bearer {GITHUB_TOKEN}", "Accept": "application/vnd.github+json"}
    res = requests.post(url, headers=headers, json=data)
    if res.status_code != 201:
        print("❌ Failed to create PR:", res.text)
        return None
    pr_url = res.json()["html_url"]
    with open("output/pr_url.txt", "w") as f:
        f.write(pr_url)
    print(f"✅ PR created: {pr_url}")
    return pr_url

if __name__ == "__main__":
    create_branch()
    if apply_ai_fix():
        create_pr()
