#!/usr/bin/env bash

# Purpose:
#
# Should be ran first when checking out the project, runs bootstrap and builds contains

set -e
[ -z "${DEBUG}" ] || set -x

cd "$(dirname "$0")/.."

docker-compose down
