#!/usr/bin/env bash

# Purpose:
#
# Used to setup the project for the very first time when checked out.

set -e
[ -z "${DEBUG}" ] || set -x

cd "$(dirname "$0")/.."

FIRST_TIME=[ ! -f /tmp/foo.txt ]

if $FIRST_TIME; then
    echo "--> copying .env.example file"

    cp .env.example .env
fi

echo "--> scripts/setup: Running setup"

scripts/setup

if $FIRST_TIME; then
    echo "--> generating Laravel encryption key"

    docker-compose exec app php artisan key:generate
fi
