#!/usr/bin/env bash

# Purpose:
#
# [DEPRECATED: Use setup instead]
# Used to setup the project for the very first time when checked out.

set -e
[ -z "${DEBUG}" ] || set -x

cd "$(dirname "$0")/.."

scripts/setup
