#!/usr/bin/env bash

# Purpose:
#
# Should be ran first when checking out the project, runs bootstrap and builds contains

set -e
[ -z "${DEBUG}" ] || set -x

cd "$(dirname "$0")/.."

if [ ! -f .env ]; then
    FIRST_TIME=true
    echo "--> copying .env.example file"

    cp .env.example .env
fi

echo "--> scripts/bootstrap: Bootstrapping application"

scripts/bootstrap

echo "--> Done"

echo "--> scripts/build: Building all docker compose services"

scripts/build

echo "--> Done"

echo "--> scripts/serve: Launching containers"

scripts/serve

echo "--> Done"

echo "--> scripts/update: Installing application dependencies"

scripts/update

echo "--> Done"

if grep -q "APP_KEY=\\n" .env; then
    echo "--> generating Laravel encryption key"

    docker-compose exec app php artisan key:generate
fi

