#!/usr/bin/env bash

# Purpose:
#
# Should be ran first when checking out the project, runs bootstrap and builds contains

set -e
[ -z "${DEBUG}" ] || set -x

cd "$(dirname "$0")/.."

echo "--> scripts/bootstrap: Bootstrapping application"

scripts/bootstrap

echo "--> Done"

echo "--> scripts/build: Building all docker compose services"

scripts/build

echo "--> Done"

echo "--> scripts/update: Installing application dependencies"

scripts/update

echo "--> Done"

echo "--> scripts/serve: Launching containers"

scripts/serve

echo "--> Containers running..."

echo "--> Done"
