#!/usr/bin/env bash

# Purpose:
#
# Copies the static assets folder to the public folder
#
# Reason:
#
# Doesn't copy during watch task

set -e
[ -z "${DEBUG}" ] || set -x

echo "--> scripts/static: Copying static assets to public folder"

cd "$(dirname "$0")/.."

cp -a resources/assets/static public/assets

echo "--> Done"
