#!/usr/bin/env bash

# Purpose:
#
# Starts tests in running app container.

set -e
[ -z "${DEBUG}" ] || set -x

cd "$(dirname "$0")/.."

echo "--> Running static analyser:"
docker-compose exec app php artisan code:analyse

echo "--> Running PHPUnit:"
docker-compose exec app php ./vendor/bin/phpunit $@
