#!/usr/bin/env bash

# Purpose:
#
# Installs application dependencies inside app container.

set -e
[ -z "${DEBUG}" ] || set -x

cd "$(dirname "$0")/.."

echo "Updating build dependencies"
./scripts/build yarn install

echo -e "\nUpdating application dependencies"
docker compose exec app php /usr/bin/composer install --prefer-dist

echo -e "\nUpdating Database"
./scripts/console migrate:fresh --seed

echo -e "\nGenerating IDE helpers"
./scripts/console ide-helper:generate
