#!/usr/bin/env bash

# Purpose:
#
# Installs dependencies inside application container.

set -e
[ -z "${DEBUG}" ] || set -x

cd "$(dirname "$0")/.."

./scripts/build yarn install
docker-compose exec app php /usr/bin/composer install --prefer-dist --no-suggest
docker-compose exec app php artisan migrate:fresh --seed
