<?php
namespace App\Http\Controllers;
use App\Models\{AuditLog,Building,CashHandover,Customer,Delivery,Invoice,Payment}; use App\Enums\PaymentMode; use Barryvdh\DomPDF\Facade\Pdf; use Illuminate\Http\Request; use PhpOffice\PhpSpreadsheet\Spreadsheet; use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
class ReportController extends Controller {
 public function data(Request $r,string $report){[$head,$rows]=$this->rows($r,$report);return response()->json(['data'=>compact('head','rows')]);}
 public function export(Request $r,string $report,string $format){[$head,$rows]=$this->rows($r,$report);abort_unless(in_array($format,['csv','xlsx','pdf']),404);$name=$report.'-'.now()->format('Ymd-His');if($format==='pdf')return Pdf::loadView('reports.pdf',compact('report','head','rows'))->download($name.'.pdf');$sheet=new Spreadsheet();$sheet->getActiveSheet()->fromArray([$head,...$rows]);if($format==='xlsx'){$path=tempnam(sys_get_temp_dir(),'mealflow-report');(new Xlsx($sheet))->save($path);return response()->download($path,$name.'.xlsx')->deleteFileAfterSend();}$stream=fopen('php://temp','w+');fputcsv($stream,$head);foreach($rows as $row)fputcsv($stream,$row);rewind($stream);return response(stream_get_contents($stream),200,['Content-Type'=>'text/csv','Content-Disposition'=>'attachment; filename="'.$name.'.csv"']);}
 private function rows(Request $r,string $report):array{$from=$r->date('from')??today()->startOfMonth();$to=$r->date('to')??today()->endOfMonth();return match($report){
  'deliveries'=>[['Date','Customer','Building','Room','Meal','Qty','Status','Employee'],Delivery::with(['customer.building','customer.room','recorder'])->whereBetween('delivery_date',[$from,$to])->get()->map(fn($x)=>[$x->delivery_date->format('Y-m-d'),$x->customer->name,$x->customer->building->name,$x->customer->room->number,$x->meal_option,$x->quantity,$x->status->value,$x->recorder->name])->all()],
  'billing'=>[['Invoice','Customer','Period','Charges','Paid','Balance','Status'],Invoice::with('customer')->whereBetween('period_start',[$from,$to])->get()->map(fn($x)=>[$x->invoice_number,$x->customer->name,$x->period_start->format('Y-m-d').' - '.$x->period_end->format('Y-m-d'),$x->current_charges,$x->amount_paid,$x->balance,$x->status->value])->all()],
  'collections'=>[['Date','Employee','Mode','Transactions','Total'],Payment::with('employee')->whereBetween('paid_at',[$from->copy()->startOfDay(),$to->copy()->endOfDay()])->get()->groupBy(fn($x)=>$x->paid_at->format('Y-m-d').'|'.$x->employee_id.'|'.$x->mode->value)->map(fn($g)=>[$g->first()->paid_at->format('Y-m-d'),$g->first()->employee->name,$g->first()->mode->value,$g->count(),$g->sum('amount')])->values()->all()],
  'outstanding'=>[['Customer','Building','Room','Outstanding'],Customer::with(['building','room'])->withSum('invoices as outstanding','balance')->get()->map(fn($x)=>[$x->name,$x->building->name,$x->room->number,$x->outstanding??0])->all()],
  'cash-pending'=>[['Employee','Submitted','Verified','Variance','Status'],CashHandover::with('employee')->whereBetween('created_at',[$from->copy()->startOfDay(),$to->copy()->endOfDay()])->get()->map(fn($x)=>[$x->employee->name,$x->amount_submitted,$x->verified_amount,$x->variance,$x->status->value])->all()],
  'building-meals'=>[['Building','Morning','Evening','Total'],Building::query()->get()->map(function($b)use($from,$to){$counts=Delivery::whereHas('customer',fn($q)=>$q->where('building_id',$b->id))->whereBetween('delivery_date',[$from,$to])->where('status','delivered')->selectRaw('meal_option,SUM(quantity) qty')->groupBy('meal_option')->pluck('qty','meal_option');$m=(int)($counts['morning']??0);$e=(int)($counts['evening']??0);return [$b->name,$m,$e,$m+$e];})->all()],
  'customer-statement'=>$this->customerStatement($r,$from,$to),
  'payment-status'=>[['Customer','Building','Room','Status','Balance'],Customer::with(['building','room','invoices'=>fn($q)=>$q->latest('period_start')->limit(1)])->get()->map(fn($c)=>[$c->name,$c->building->name,$c->room->number,$c->invoices->first()?->status?->value??'no_invoice',$c->invoices->first()?->balance??0])->all()],
  'building-outstanding'=>[['Building','Outstanding'],Building::query()->select('buildings.id','buildings.name')->selectRaw('COALESCE(SUM(invoices.balance),0) as outstanding')->leftJoin('customers','customers.building_id','=','buildings.id')->leftJoin('invoices','invoices.customer_id','=','customers.id')->groupBy('buildings.id','buildings.name')->orderByDesc('outstanding')->get()->map(fn($b)=>[$b->name,$b->outstanding])->all()],
  'revenue-summary'=>$this->revenueSummary($from,$to),
  'audit-log'=>[['Date','User','Action','Entity','Entity ID','IP'],AuditLog::with('user')->whereBetween('created_at',[$from->copy()->startOfDay(),$to->copy()->endOfDay()])->latest()->limit(1000)->get()->map(fn($a)=>[$a->created_at->format('Y-m-d H:i:s'),$a->user->name??'system',$a->action,class_basename($a->auditable_type??''),$a->auditable_id,$a->ip_address])->all()],
  default=>abort(404)};}
 private function customerStatement(Request $r,$from,$to):array{$customer=Customer::where('uuid',$r->get('customer'))->firstOrFail();$entries=$customer->ledger()->whereBetween('created_at',[$from->copy()->startOfDay(),$to->copy()->endOfDay()])->latest('id')->get();return [['Date','Type','Description','Debit','Credit','Balance'],$entries->map(fn($e)=>[$e->created_at->format('Y-m-d H:i'),$e->type,$e->description,$e->debit,$e->credit,$e->running_balance])->all()];}
 private function revenueSummary($from,$to):array{$rows=Payment::whereNull('reverses_payment_id')->whereBetween('paid_at',[$from->copy()->startOfDay(),$to->copy()->endOfDay()])->get()->groupBy(fn($p)=>$p->paid_at->format('Y-m-d'));return [['Date','Cash','Card','Total'],$rows->map(function($g,$d){$cash=(float)$g->where('mode',PaymentMode::Cash)->sum('amount');$card=(float)$g->where('mode',PaymentMode::Card)->sum('amount');return [$d,$cash,$card,$cash+$card];})->values()->all()];}
}
