<?php
namespace App\Http\Controllers\Web;
use App\Enums\Role; use App\Http\Controllers\Controller; use App\Models\{Building,Company,Customer,MealPlan,Room,User}; use App\Services\AuditService; use Illuminate\Http\Request; use Illuminate\Support\Facades\DB; use Illuminate\Support\Facades\Hash; use Illuminate\Validation\Rule;
class AdminController extends Controller {
 public function companies(){abort_unless(auth()->user()->isPlatformAdmin(),403);return view('admin.index',['title'=>'Companies','columns'=>['name','code','currency','timezone','is_active'],'rows'=>Company::latest()->paginate(30),'create'=>'companies']);}
 public function storeCompany(Request $r){abort_unless(auth()->user()->isPlatformAdmin(),403);$d=$r->validate(['name'=>'required|max:150','code'=>'required|max:30|alpha_dash|unique:companies,code','admin_name'=>'required|max:150','admin_email'=>'required|email|unique:users,email','password'=>'required|min:12']);DB::transaction(function()use($d){$c=Company::create(['name'=>$d['name'],'code'=>$d['code']]);User::create(['company_id'=>$c->id,'name'=>$d['admin_name'],'email'=>$d['admin_email'],'password'=>Hash::make($d['password']),'role'=>Role::CompanyAdmin]);});return back()->with('status','Company created.');}
 public function buildings(){return view('admin.index',['title'=>'Buildings','columns'=>['name','code','address','is_active'],'rows'=>Building::latest()->paginate(30),'create'=>'buildings']);} public function storeBuilding(Request $r){$d=$r->validate(['name'=>'required|max:150','code'=>'required|max:30','address'=>'nullable|max:500']);Building::create($d);return back()->with('status','Building created.');}
 public function rooms(){return view('admin.index',['title'=>'Rooms','columns'=>['building.name','number','floor','capacity','delivery_enabled'],'rows'=>Room::with('building')->latest()->paginate(30),'create'=>'rooms','buildings'=>Building::orderBy('name')->get()]);} public function storeRoom(Request $r){$d=$r->validate(['building_id'=>'required|exists:buildings,id','number'=>'required|max:50','floor'=>'nullable|max:50','capacity'=>'required|integer|min:1|max:1000']);Room::create($d);return back()->with('status','Room created.');}
 public function customers(){return view('admin.index',['title'=>'Customers','columns'=>['customer_code','name','masked_passport','phone','building.name','room.number','is_active'],'rows'=>Customer::with(['building','room'])->latest()->paginate(30),'create'=>'customers','buildings'=>Building::orderBy('name')->get(),'rooms'=>Room::orderBy('number')->get()]);} public function storeCustomer(Request $r){$d=$r->validate(['customer_code'=>'required|max:50','name'=>'required|max:150','passport_number'=>'required|max:100','phone'=>'nullable|max:30','building_id'=>'required|exists:buildings,id','room_id'=>'required|exists:rooms,id','start_date'=>'required|date','opening_balance'=>'nullable|decimal:0,2']);$room=Room::findOrFail($d['room_id']);abort_unless($room->building_id==(int)$d['building_id'],422,'Room does not belong to building.');abort_if($room->customers()->where('is_active',true)->count()>=$room->capacity,422,'Room capacity reached.');Customer::create($d);return back()->with('status','Customer created.');}
 public function plans(){return view('admin.index',['title'=>'Meal Plans','columns'=>['name','meal_option','billing_type','daily_rate','monthly_rate','is_active'],'rows'=>MealPlan::latest()->paginate(30),'create'=>'plans']);} public function storePlan(Request $r){$d=$r->validate(['name'=>'required|max:150','meal_option'=>'required|in:morning,evening,both','billing_type'=>'required|in:fixed_monthly,delivered_daily','daily_rate'=>'nullable|decimal:0,2|min:0','monthly_rate'=>'nullable|decimal:0,2|min:0','credit_pauses'=>'nullable|boolean','credit_skips'=>'nullable|boolean']);MealPlan::create([...$d,'credit_pauses'=>$r->boolean('credit_pauses'),'credit_skips'=>$r->boolean('credit_skips')]);return back()->with('status','Meal plan created.');}
 public function employees(){return view('admin.index',['title'=>'Employees','columns'=>['name','email','phone','role','is_active'],'rows'=>User::where('company_id',auth()->user()->company_id)->orderBy('name')->paginate(30),'create'=>'employees','buildings'=>Building::orderBy('name')->get()]);}
 public function storeEmployee(Request $r){$d=$r->validate(['name'=>'required|max:150','email'=>'required|email|unique:users,email','phone'=>'nullable|max:30','password'=>'required|min:12','role'=>['required',Rule::enum(Role::class)],'building_ids'=>'array','building_ids.*'=>'exists:buildings,id']);abort_if($d['role']===Role::PlatformAdmin->value,422);$u=User::create(['name'=>$d['name'],'email'=>$d['email'],'phone'=>$d['phone']??null,'password'=>Hash::make($d['password']),'role'=>$d['role'],'company_id'=>auth()->user()->company_id]);$u->buildings()->syncWithPivotValues($d['building_ids']??[],['company_id'=>auth()->user()->company_id]);AuditService::record('employee.created',$u);return back()->with('status','Employee created.');}
 public function toggleEmployee(Request $r,User $employee){abort_unless($employee->company_id===auth()->user()->company_id,404);$employee->update(['is_active'=>!$employee->is_active]);AuditService::record('employee.toggled',$employee);return back()->with('status',$employee->is_active?'Employee re-enabled.':'Employee disabled.');}
 public function updateBuilding(Request $r,Building $building){$d=$r->validate(['name'=>'required|max:150','code'=>'required|max:30','address'=>'nullable|max:500','contact_person'=>'nullable|max:150','is_active'=>'nullable|boolean']);$building->update([...$d,'is_active'=>$r->boolean('is_active')]);AuditService::record('building.updated',$building);return back()->with('status','Building updated.');}
 public function updateRoom(Request $r,Room $room){$d=$r->validate(['number'=>'required|max:50','floor'=>'nullable|max:50','capacity'=>'required|integer|min:1|max:1000','delivery_enabled'=>'nullable|boolean']);$room->update([...$d,'delivery_enabled'=>$r->boolean('delivery_enabled')]);AuditService::record('room.updated',$room);return back()->with('status','Room updated.');}
 public function updateCustomer(Request $r,Customer $customer){$d=$r->validate(['name'=>'required|max:150','phone'=>'nullable|max:30','room_id'=>'required|exists:rooms,id','is_active'=>'nullable|boolean']);$room=Room::findOrFail($d['room_id']);$customer->update(['name'=>$d['name'],'phone'=>$d['phone']??null,'room_id'=>$room->id,'building_id'=>$room->building_id,'is_active'=>$r->boolean('is_active'),'deactivated_at'=>$r->boolean('is_active')?null:($customer->deactivated_at??today())]);AuditService::record('customer.updated',$customer);return back()->with('status','Customer updated.');}
 public function updatePlan(Request $r,MealPlan $plan){$d=$r->validate(['name'=>'required|max:150','daily_rate'=>'nullable|decimal:0,2|min:0','monthly_rate'=>'nullable|decimal:0,2|min:0','is_active'=>'nullable|boolean']);$plan->update([...$d,'is_active'=>$r->boolean('is_active')]);AuditService::record('meal_plan.updated',$plan);return back()->with('status','Meal plan updated.');}
}
