name: Pull Requests

on:
  pull_request_target:
    types: [opened]

permissions:
  pull-requests: write

jobs:
  uneditable:
    uses: laravel/.github/.github/workflows/pull-requests.yml@2cb86405a12fc5a4ec114ec26d41a790cdcbc2fa # main
